name: "PR Checklist Validation"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write   # needed only if posting comments; safe for org repos
  discussions: write     # optional, for commenting in some setups

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Validate required checkbox in PR body
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const core = require('@actions/core');

            const payloadPr = context.payload.pull_request;
            if (!payloadPr) {
              core.info("No pull_request object in payload — nothing to validate.");
              return;
            }

            const prNumber = payloadPr.number;
            const prBody = payloadPr.body || "";
            // CONFIG: set to exact checkbox label (e.g. "Security review completed"), or "any"
            const REQUIRED_CHECKBOX = (process.env.REQUIRED_CHECKBOX || "any").trim();
            // CONFIG: set to "true" to have the action post a helpful comment when missing
            const POST_COMMENT = (process.env.POST_COMMENT || "true").toLowerCase() === "true";

            function escapeRegExp(string) {
              return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
            }

            let checklistOk = false;
            if (REQUIRED_CHECKBOX.toLowerCase() === "any") {
              checklistOk = /\- \[[xX]\]\s+/.test(prBody);
            } else {
              const pattern = new RegExp(`- \\[[xX]\\]\\s*${escapeRegExp(REQUIRED_CHECKBOX)}`);
              checklistOk = pattern.test(prBody);
            }

            if (!checklistOk) {
              const message =
                REQUIRED_CHECKBOX.toLowerCase() === "any"
                  ? "Please check at least one checkbox in the PR Checklist (required before merging)."
                  : `Please check the required checklist item in the PR description: "${REQUIRED_CHECKBOX}".`;

              core.setFailed(message);

              if (POST_COMMENT) {
                try {
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: prNumber,
                    body: `🔒 Merge blocked — ${message}\n\nIf this is already done, please re-save the PR description or push a tiny update to retrigger checks.`
                  });
                } catch (err) {
                  core.info(`Failed to post comment: ${err.message}`);
                }
              }
            } else {
              core.info("Checklist requirement satisfied.");
              // Optionally remove previous "blocked" comments — omitted to keep example simple
            }
        env:
          # Change this to the exact checkbox label you require, or "any"
          REQUIRED_CHECKBOX: "Security review completed"
          # Set to "false" to disable action comments
          POST_COMMENT: "true"
