name: "PR Checklist Validation"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-checklist:
    runs-on: ubuntu-latest
    name: Validate required checklist item
    steps:
      - name: Check required checkbox in PR body
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prBody = context.payload.pull_request && context.payload.pull_request.body || "";
            const anyChecked = /\- \[[xX]\]\s+/.test(prBody);
            if (!anyChecked) {
              core.setFailed("No checklist item is checked in the PR body. Please check at least one checkbox in the Checklist section before merging.");
            } else {
              core.info("At least one checkbox is checked.");
            }
