name: Require Acknowledge Checkbox

on:
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled]

jobs:
  check_acknowledge:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for acknowledge checkbox
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || "";
            const acknowledged = /\[x\]\s*I acknowledge/.test(prBody);
            if (!acknowledged) {
              core.setFailed("You must check the 'I acknowledge' checkbox before merging.");
            }
